### ISSUE TITLE
format: date-time is not applied when using dates from generators.

### ISSUE THREAD

**Issue by atomsfat** [json-schema-faker/json-schema-faker#476]
Given:
```yaml
 endDate:
    type: string
    format: date-time
    faker: 'date.past'
```
You got
```
"endDate": "Sat Feb 03 2018 21:33:06 GMT-0600 (CST)"
```

The format is not applied when using dates from generators.

json-schema-faker: 0.5.0-rc16
faker: 4.1.0

Fixed no on master 4c56762b3dff200186db32dadb00f800befff1e7 just to track.
