### ISSUE TITLE
Prop `maxProperties` is being ignored as`additionalProperties` for maps aren't being generated.

### ISSUE THREAD

**Issue by rodoabad** [json-schema-faker/json-schema-faker#504]
If you are reporting a bug, please include the following:

1. the JSON Schema content that fails - preferably using http://json-schema-faker.js.org/ (paste the schema, click `Generate example` and then copy and paste the resulting URL from the browser address bar)

```
type: object
properties:
  rodo:
    type: string
required:
  - rodo
additionalProperties:
  type: boolean
  minProperties: 2
  maxProperties: 100
```

2. the result you got

```
{
  "rodo": "sed aute dolore est in"
}
```
3. the result you expected
```
{
  "rodo": "sed aute dolore est in",
  "gsegrsg": true,
  "hrtesdgfzg" false
}
```
