### ISSUE TITLE
Custom uuid

### ISSUE THREAD

**Issue by Sebastiencreoff** [json-schema-faker/json-schema-faker#616]
Hello,  I discover json-schema-faker this morning which looks amazing for dynamic response generation. 
I am working on  a project where I defined a field like that based on OpenApi definition.

```
   ObjectId:
      type: string
      description: "my object."
      minLength: 36
      maxLength: 36
      example: obj_00000000000000000000000000000000
      pattern: ^(cpg|xpg)_[0-9a-f]{32}$
```

I was looking at the documentation to find a way to generate dynamically this field and I do not find it. Maybe could someone help me about that ? Any help would be appreciated.

Thanks,
Sebastien
